const BY_CITY = 'SEARCH BY CITY';
const BY_COUNTRY = 'SEARCH BY COUNTRY';
const ENTER_CITY = 'Enter a city';
const ENTER_COUNTRY = 'Enter a country';
const COUNTRY_CODE = 'PCLI';
const CITY_CODE = 'PPL';

export {
  BY_CITY, BY_COUNTRY, ENTER_CITY, ENTER_COUNTRY, COUNTRY_CODE, CITY_CODE
};